export const diretrizes='DIRETRIZES DO PROJETO ESCUTA \n'+
'O PROJETO ESCUTA espera que você, como psicólogo(a) voluntário(a), ao receber um encaminhamento alguém que precisa de ajuda, confirme sua disponibilidade para o agendamento da sessão. Esse atendimento deve estar de acordo com as nossas diretrizes:\n'+
'● O/A psicólogo/a deve seguir todos os princípios éticos e profissionais da psicologia conforme determinam as normas aplicáveis, as recomendações do Conselho Federal de Psicologia e o Código Profissional de Ética da Psicologia, especialmente a resolução CFP no 011/2012 e CFP no 011/2018, que regulamenta o atendimento psicológico remoto além de outras normas que possam vir a ser aplicadas enquanto durar sua participação no projeto.\n'+
'● O/A psicólogo/a se compromete em realizar todos os atendimentos realizados via PROJETO ESCUTA de forma voluntária.\n'+
'●  O/A psicólogo/a deve estar regularmente inscrito/a no Conselho Federal de Psicologia (CFP),estando, portanto, autorizada(o) pelo órgão a fazer atendimentos psicológicos no território nacional.\n'+
'● O/A psicólogo/a deve estar habilitado/a no e-Psi (cadastro que permite prestação de serviços psicológicos realizados por meio de tecnologias da informação e da comunicação). \n'+
'● A plataforma oficial utilizada pelo Instituto Não Me Esqueças para realização dos atendimentos virtuais é GoToMeeting. Este recurso não gera custo para os/as psicólogos/as, é de  boa qualidade, fácil de instalar e a internet lenta suporta. Também é possível compartilhar a tela com o/a assistido/a para mostrar textos, atividades e outros instrumentos e técnicas que estão arquivados no computador do trabalho. O/A assistido/a só consegue contato pelo link específico que é temporário, evitando contatos sem agendamento.\n'+
'● Para o atendimento online é necessário que o/a psicólogo/a tenha acesso à internet e celular ou computador com microfone e câmera (se necessário).\n'+
'● O/A psicólogo/a receberá uma mensagem no email com o link do atendimento e deverá aguardar o/a assistido/a no horário agendado.\n'+
'● O local de atendimento deve ser sigiloso, seguro, privativo, confortável, sem circulação de pessoas, com isolamento acústico (sem barulho que possa distrair ), evitando interferências e interrupções. Sempre respeitando as cláusulas do Código de Ética da profissão.\n'+
'● Caso o/a psicólogo/a tenha que interromper o atendimento é preciso comunicar imediatamente o Instituto Não Me Esqueças, para que outro/a voluntário/a habilitado/a seja localizado/a para assumir o atendimento;\n'+
'● O/A psicólogo/a se compromete a realizar um atendimento humanizado com escuta ativa e qualificada, entendendo as peculiaridades do caso, independente da linha psicológica escolhida. O/A psicólogo/a deve sempre respeitar a autonomia e a vontade do/a assistido/a, para que ele/a decida qual caminho quer seguir;\n'+
'● O/A psicólogo/a deve avaliar os fatores de risco que permeiam o caso concreto, levando em conta questões raciais, vulnerabilidade social, identidade de gênero e orientação sexual;\n'+
'● É vedado induzir o atendimento à convicções políticas, filosóficas, morais, ideológicas, religiosas, de orientação sexual e/ou propagar qualquer tipo de preconceito; a utilização dos atendimentos para fins político-partidários ou eleitorais, bem como instrumento de publicidade para captação de clientela;\n'+
'● É expressamente proibido o uso de técnicas terapêuticas não regulamentadas ou reconhecidas pelo CFP e que não são previstas como prática psicológica tais como regressão, aplicação de testes psicológicos não oficiais e práticas que envolvam fé ou misticismo (astrologia, tarô, terapia de vidas passadas etc);\n'+
'● É expressamente proibido o compartilhamento de informações sigilosas referentes ao atendimento como áudios, imagens, documentos e dados capazes de identificar as pessoas assistidas;\n'+
'● Caso haja qualquer alteração dos seus dados cadastrais como telefone, endereço e disponibilidade etc ou queira se descadastrar do projeto, o/a psicólogo/a deve informar à equipe do Instituto Não Me Esqueças pelo email p.psiconecte@gmail.com'


export const termoDeAdesao='TERMO DE ADESÃO  AO  VOLUNTARIADO \n'+
'Pelo presente Termo de Adesão ao Voluntariado, TERMO, daqui para frente,  eu, psicólogo(a) voluntário(a) e o Instituto Não Me Esqueças acordam em oferecer em conjunto apoio e acolhimento virtual a pessoas com 60 anos ou mais e seus cuidadores(as)  informais  ou formais, conforme define o item 1 deste TERMO.'+
'Entende-se por ASSISTIDO(S) as pessoas com 60 anos ou mais, cuidadores(as) formais de idosos (pessoas remuneradas para realização dos cuidados) e cuidadores(as) informais de idosos (pessoas não remuneradas para realização dos cuidados) que se cadastram no aplicativo PROJETO ESCUTA para atendimento psicológico gratuito, pontual e informativo;'+
'Entende-se por VOLUNTÁRIO(S) os(as) psicólogos(as) que integram o PROJETO ESCUTA para atendimento aos ASSISTIDOS.'+
'Entende-se por ATENDIMENTO o encontro virtual e pontual realizado por VOLUNTÁRIOS que visam à escuta e ao acolhimento das demandas trazidas pelos ASSISTIDOS, de maneira inteiramente gratuita e voluntária.'+
'Denomina-se PARTE TITULAR o Instituto Não Me Esqueças, PARTE VINCULADA o VOLUNTÁRIO, e PARTES o Instituto e o VOLUNTÁRIO, em conjunto.'+

'Assim posto, nos termos da Lei de Voluntariado (Lei n. 9.608/1998), da Resolução CFP 011/2018 e Resolução CFP No 011/2012 (Conselho Federal de Psicologia) as PARTES firmam as condições do trabalho voluntário a ser realizado, conforme estabelecido a seguir.\n'+
'1. Sobre o trabalho voluntário no PROJETO ESCUTA'+
'1.1. O objeto deste TERMO consiste na realização do ATENDIMENTO por parte do VOLUNTÁRIO perante os ASSISTIDOS, de maneira inteiramente gratuita e voluntária, reconhecendo a ausência da caracterização de qualquer vínculo empregatício, ou de quaisquer outras obrigações de natureza trabalhista, previdenciária ou afins.\n'+
'As atribuições do VOLUNTÁRIO na realização do ATENDIMENTO são:\n'+
'Atendimento psicológico pontual e virtual, prestando uma escuta ativa e o acolhimento necessário.\n'+
'O VOLUNTÁRIO se compromete em realizar o encaminhamento do ASSISTIDO para uma instituição da rede de serviços de atendimento caso verifique situação de risco iminente, de acordo com a resolução 011/2018 do CFP.\n'+
'2. Duração\n'+
'2.1. Vigência. O presente TERMO vigorará por tempo indeterminado, a contar da data de sua assinatura, podendo ser rescindido por qualquer das partes, conforme 2.2.\n'+
'2.2. Resilição. O TERMO poderá ser rescindido por meio de aviso prévio à PARTE contrária com, no mínimo, 05 (cinco) dias de antecedência, com exceção da hipótese prevista na cláusula 4.4 \“b\”.\n'+
'3. Compromissos do Instituto Não Me esqueças.\n'+
'3.1 O Instituto Não Me Esqueças não ressarcirá quaisquer despesas provenientes do desempenho da atividade  de ATENDIMENTO, exceto aquelas que tenham sido prévia e expressamente autorizadas por escrito pela PARTE TITULAR. As despesas que vierem a ser apresentadas para reembolso e que forem autorizadas pelo Instituto deverão ser comprovadas por meio de instrumento fiscal.\n'+
'4. Compromissos no Atendimento.\n'+
'4.1. O VOLUNTÁRIO: \n'+
'a. Entende e concorda que, ao realizar qualquer ATENDIMENTO, deve seguir todos os princípios éticos e profissionais da psicologia conforme determinam as normas aplicáveis, as recomendações do Conselho Federal de Psicologia e o Código Profissional de Ética da Psicologia, especialmente a resolução CFP no 011/2012 e CFP no 011/2018, que regulamenta o atendimento psicológico remoto além de outras normas que possam vir a ser aplicadas doravante;\n'+
'b. Compreende que o ATENDIMENTO deve ser integralmente gratuito;\n'+
'c. Se compromete a realizar um atendimento humanizado, entendendo as peculiaridades do caso, independente da técnica psicológica escolhida.\n'+
'd. Entende que para realização dos atendimentos virtuais é necessário que tenha acesso à internet e computador com microfone e câmera.\n'+
'e. Compreende que, ao prestar serviços aos ASSISTIDOS, declara estar ciente de que não é permitido vinculá-los ou condicioná-los à contratação de serviços remunerados, em qualquer circunstância ou sob qualquer hipótese;\n'+
'f. Compreende e concorda que é vedada a utilização dos ATENDIMENTOS para fins político-partidários ou eleitorais, bem como instrumento de publicidade para captação de clientela;\n'+
'g. Compreende e concorda que é vedado induzir convicções políticas, filosóficas, morais, ideológicas, religiosas, de orientação sexual, de identidade de gênero e/ou propagar qualquer tipo de preconceito;\n'+
'h. Compreende e concorda que o ATENDIMENTO será realizado com o propósito de acolher o ASSISTIDO e que é terminantemente proibido utilizar deste atendimento para qualquer outra finalidade que não a escuta qualificada e respeitosa. Se por razões de foro pessoal o VOLUNTÁRIO entender que não poderá oferecer atendimento no melhor interesse do ASSISTIDO, deverá imediatamente comunicar este fato à equipe Instituto Não Me Esqueças, pelo criaremail@gmail.com, permitindo que o caso seja redirecionado para outro VOLUNTÁRIO, de acordo com a cláusula 4.3 deste TERMO.\n'+
'i. Declara estar regularmente inscrito no Conselho Federal de Psicologia (“CFP”) e inscrito no "e-psi" (cadastro que permite prestação de serviços psicológicos realizados por meio de tecnologias da informação e da comunicação), sendo que este último independe de aprovação do CFP, conforme resoluções CFP no 11/2012 e CFP no 11/2018, estando, portanto, autorizado pelo órgão a fazer atendimentos psicológicos remotos no território nacional.\n'+
'j. Entende que é expressamente proibida pelo CFP a realização de atendimento online para pessoas que estejam em situação expressa de violação de direitos.\n'+
'k. Entende que é expressamente proibido o uso de técnicas terapêuticas não regulamentadas ou reconhecidas pelo CFP e que não são previstas como prática psicológica tais como regressão, aplicação de testes psicológicos não oficiais e práticas que envolvam fé ou misticismo (astrologia, tarô, terapia de vidas passadas etc). \n'+
'4.2. Disponibilidade. Ao aceitar qualquer ATENDIMENTO, o VOLUNTÁRIO deve avaliar a sua disponibilidade para acolher o ASSISTIDO para que ele não necessite de outro encaminhamento.\n'+
'4.3. Encaminhamentos. Caso seja necessário encaminhar o ASSISTIDO a outro profissional, a equipe do Instituto Não Me Esqueças deverá ser informada imediatamente para que outro VOLUNTÁRIO habilitado seja acionado. Isso deve ser feito apenas como último recurso.\n'+
'4.4. Diversidade. Ao acolher um ASSISTIDO, o VOLUNTÁRIO se compromete a dedicar o tempo que for necessário levando em conta questões raciais, vulnerabilidade social, identidade de gênero e orientação sexual. Estas diferenças devem ser reconhecidas uma vez que apresentam variáveis importantes no processo de cura.\n'+
'a. Ao atender os ASSISTIDOS o VOLUNTÁRIO deve se atentar para não reproduzir violências. Isso\n'+
'inclui respeitar o nome social e gênero de mulheres travestis, transexuais, transgênero assim como de pessoas intersexo, não binárias entre outros, caso se enquadre no ATENDIMENTO.\n'+
'b. O VOLUNTÁRIO se compromete a oferecer o melhor ATENDIMENTO, dentro de suas capacidades, independente da cor, raça, etnia, deficiência, religião, nacionalidade, orientação sexual, identidade de gênero ou qualquer outra característica do ASSISTIDO, entendendo que atos de preconceito e/ou discriminação poderão ensejar em responsabilização civil ou criminal conforme determina a legislação brasileira, além do desligamento do VOLUNTÁRIO ao programa de voluntariado junto Instituo Não Me Esqueças, independente de aviso prévio, conforme mencionado na Cláusula de Sanções deste TERMO.\n'+
'4.5. Reputação do PROJETO ESCUTA. A utilização indevida do nome do Instituto Não Me Esqueças pode ensejar em penalidades, conforme mencionado na Cláusula de Sanções deste TERMO.\n'+
'5. Confidencialidade e Proteção das Informações\n'+
'5.1. As PARTES obrigam-se a respeitar sempre e a qualquer tempo, o caráter confidencial e sigiloso de todas as informações, instalações, dados, cópias de documentos dos ASSISTIDOS que passarem por ATENDIMENTO, assim como, papéis relativos ao presente TERMO que direta ou indiretamente forem levados ao seu conhecimento (“Informações Confidenciais”). As PARTES comprometem-se a não divulgar a terceiros estas informações, salvo se houver prévia autorização por escrito da PARTE  TITULAR.\n'+
'5.2. No caso de divulgação autorizada de Informações Confidenciais, conforme o item 5.1. deste TERMO, a PARTE que divulgar a informação a terceiros deverá exigir deste a mesma obrigação de sigilo e confidencialidade, respondendo, solidariamente, pelos atos praticados por terceiros que violem esta obrigação.\n'+
'5.3. As PARTES usarão as Informações Confidenciais apenas para a consecução dos objetivos deste TERMO, obrigando-se a tomar todas as providências cabíveis no sentido de manter em sigilo e não as revelar, total ou parcialmente, respondendo pela violação do sigilo ou pelo uso para propósito diverso do previsto no TERMO.\n'+
'5.4. Nenhuma das PARTES será responsabilizada pela divulgação de informações nas seguintes hipóteses:\n'+
'(i) Se a informação for comprovadamente do conhecimento da PARTE receptora, antes de ser revelada pela outra PARTE, e sem violação de qualquer obrigação de sigilo;\n'+
'(ii) Se a informação tiver sido legalmente obtida de terceiros, sem inobservância de qualquer das disposições deste TERMO;\n'+
'(iii) Se a informação está ou se tornou disponível ao público de outra forma, que não em decorrência de qualquer ato ou omissão das PARTES ou das pessoas ligadas a elas.\n'+
'5.5. Nenhuma das PARTES usará o nome da outra em atividades de publicidade, propaganda ou semelhantes sem que tenha o prévio e expresso consentimento da outra.\n'+
'5.6. Cada PARTE utilizará Informações Confidenciais a que tiverem acesso por força deste TERMO somente conforme as instruções e permitido pela PARTE que as disponibilizou e somente para realizar as atividades previstas neste TERMO. As PARTES não podem utilizar Informações Confidenciais para nenhum outro propósito, incluindo e sem limitação, para seu próprio benefício comercial.\n'+
'5.7. Após o término deste TERMO, uma PARTE deve retornar para a outra PARTE, destruir ou permanentemente excluir, toda Informação Pessoal, como instruído pela PARTE responsável por escrito.\n'+
'6. Uso das Informações Confidenciais\n'+
'6.1. O VOLUNTÁRIO reconhece, entende e concorda que as Informações Confidenciais pertencem ao Instituto Não Me Esqueças.\n'+
'6.2. O VOLUNTÁRIO concorda que todas as Informações Confidenciais serão mantidas por ela em local seguro, com acesso limitado àqueles funcionários e colaboradores do Instituto Não Me Esqueças que necessitarem de tais Informações Confidenciais, e serão utilizadas exclusivamente para os fins determinados pelo Instituto Não me Esqueças.\n'+
'6.3. O VOLUNTÁRIO expressamente concorda só transmitir, comunicar, revelar ou disponibilizar, no todo ou em parte, as Informações Confidenciais para terceiros e/ou consultores, se autorizado previamente e por escrito pelo Instituto Não Me Esqueças, sendo certo que nesta hipótese os terceiros e/ou consultores deverão concordar em se submeter às obrigações previstas neste TERMO.\n'+
'6.4. O VOLUNTÁRIO não outorgará, em hipótese alguma, qualquer direito inerente às referidas informações, no todo ou em parte, permanecendo o Instituto Não Me Esqueças como legal proprietário das Informações Confidenciais e dos direitos próprios (incluindo, mas não se limitando aos direitos de patente), sendo vedado ao VOLUNTÁRIO utilizar as Informações Confidenciais em seu benefício para obter qualquer tipo de receita ou vantagem.\n'+
'6.5. Na hipótese do VOLUNTÁRIO ser obrigado, em virtude de determinação judicial, administrativa ou por força de lei, a divulgar as Informações Confidenciais, ele se compromete a notificar o Instituto Não Me Esqueças por escrito e em até 2 (dois) dias úteis do recebimento de tal determinação judicial, administrativa ou legal, a fim de que o Instituto Não Me Esqueças possa contestar a divulgação ou buscar medida judicial ou administrativa cabível para que a Informação Confidencial não seja divulgada.\n'+
'7. Devolução e Destruição de Informações Confidenciais\n'+
'7.1. No fim da vigência deste TERMO, o VOLUNTÁRIO se compromete a devolver ao Instituto Não Me Esqueças todas as Informações Confidenciais obtidas, independentemente de comunicação ou notificação nesse sentido, devendo destruir toda e qualquer cópia eventualmente existente no prazo de 72 (setenta e duas) horas contadas do fim da vigência deste TERMO.\n'+
'8. Proteção de Dados\n'+
'8.1. Dados Pessoais. O uso e o tratamento de dados e informações obtidos , seja por meio on-line ou off-line, capazes de identificar ou tornar identificáveis pessoas físicas, incluindo dados que possam ser combinados com outras informações para identificar um indivíduo, e/ou que se relacionem com a identidade, características ou comportamento de um indivíduo ou influenciem na maneira como esse indivíduo é tratado ou avaliado (os “Dados Pessoais”) se darão de acordo com a legislação brasileira vigente aplicável e com o disposto nesta cláusula. Para fins de interpretação deste TERMO, “Tratamento” terá o significado definido na Lei n° 13.709/18.\n'+
'8.2. Finalidades. As PARTES garantem que todo e qualquer uso, Tratamento e armazenamento de Dados Pessoais no âmbito deste TERMO serão realizados sempre utilizando uma base legal válida e legítima adequada ao Tratamento, podendo ser, por exemplo, com base no legítimo interesse da PARTE que tratar o Dado Pessoal (os “Usos Permitidos”) para as finalidades determinadas neste TERMO, respeitada a legislação aplicável.\n'+
'8.3. Bases legais. o VOLUNTÁRIO se compromete a: (i) não obter os Dados Pessoais sem a observância da base legal legítima de que se vale o Instituto Não Me Esqueças para o Tratamento; e (ii) não obter os Dados Pessoais em desconformidade com quaisquer leis ou regulamentações aplicáveis, declarando ainda, sem limitação, que não participou na quebra de qualquer dever de sigilo de parceiros comerciais ou instituições terceiras, incluindo sigilo financeiro e fiscal; estando ciente que o Instituto Não Me Esqueças pode tomar qualquer medida legal cabível caso seja constatada tal situação.\n'+
'8.4. Propriedade. o VOLUNTÁRIO declara estar ciente e de acordo que todos os Dados Pessoais coletados e Tratados em decorrência da execução do TERMO serão considerados de propriedade exclusiva do Instituto Não Me Esqueças.\n'+
'8.5. Incidente de Segurança. o VOLUNTÁRIO garante que cumprirá com todas as políticas, regras e orientações de segurança da informação passadas pelo Instituto Não Me Esqueças, conforme estabelecido nas normas e políticas internas do Instituto Não Me Esqueças, em especial no que concerne aos Dados Pessoais, incluindo questões relativas a armazenamento, criptografia e controles de acesso, a fim de protegê-las contra perdas, divulgações e acessos não autorizados, sejam esses acidentais ou não (o “Incidente”), devendo adotar medidas para garantir adequada segurança contra os riscos apresentados em decorrência da natureza dos Dados Pessoais. O VOLUNTÁRIO compromete-se a imediatamente informar o Instituto Não Me Esqueças em caso de ocorrência ou mera suspeita de um Incidente ou violação, dano ou Tratamento, perda, destruição, alteração ilegais ou não autorizados de Dados Pessoais. Exemplos de Incidentes podem ser furto, roubo ou invasão de dispositivos eletrônicos em que constavam dados de ATENDIMENTO ou de ASSISTIDOS.\n'+
'8.6. Exercício de Direitos. Caso algum titular dos Dados Pessoais Tratados pelo VOLUNTÁRIO no âmbito deste TERMO faça alguma requisição ao VOLUNTÁRIO no exercício de seus direitos previstos na Lei n° 13.709/18 ou em qualquer outra legislação pertinente, como por exemplo, sem limitação, solicite a alteração, atualização, correção, acesso ou exclusão de seus Dados Pessoais, o VOLUNTÁRIO deverá comunicar tal fato imediatamente ao Instituto Não Me Esqueças e proceder ao atendimento da requisição feita pelo titular dos Dados Pessoais.\n'+
'8.7. Requisição dos Dados. Caso os Dados Pessoais sejam exigidos por requisição de autoridades competentes ou por determinação judicial, o VOLUNTÁRIO deverá notificar previamente o Instituto Não Me Esqueças acerca da existência e do conteúdo da ordem/requisição correspondente.\n'+
'8.8. Segurança da Informação. Visando garantir níveis de segurança adequados no Tratamento de dados, as PARTES se comprometem a utilizar mecanismos razoáveis de segurança da informação, evitando que Dados Pessoais e outras informações sigilosas sejam obtidas de maneira irregular. Dentre estas medidas estão as seguintes, não se limitando a: utilização de senha nos dispositivos eletrônicos usados para armazenar dados dos ATENDIMENTOS, não disponibilizar estas senhas a terceiros, não acessar informações ou fazer ATENDIMENTOS utilizando dispositivos públicos ou com baixa segurança, acessar as informações relativas aos ATENDIMENTOS sempre em redes seguras, manter atualizados os antivírus e outros meios de proteção de dispositivos eletrônicos, guardar em local seguro cópias físicas de documentos relativos aos atendimentos, dentre outras medidas.\n'+
'9. Comunicação com o Instituto Não Me Esqueças\n'+
'9.1. Toda comunicação entre as partes deve ser feita utilizando-se correspondência eletrônica. \n'+
'9.2. Ao sofrer qualquer alteração dos seus dados cadastrais etc., o VOLUNTÁRIO se compromete a informar imediatamente à equipe do Instituto Não Me Esqueças pelo email: xxx@gmail.com\n'+
'9.3. Na impossibilidade de prestar o ATENDIMENTO ou havendo necessidade de interromper o ATENDIMENTO, o VOLUNTÁRIO se compromete a comunicar imediatamente a equipe do Instituto Não Me Esqueças por meio do email: xxx@gmail.com para que possam dar suporte ao ASSISTIDO.\n'+
'9.4. É expressamente proibido o compartilhamento de informações sigilosas referentes ao ATENDIMENTO como áudios, imagens, documentos e dados capazes de identificar o ASSISTIDO, sob pena de responsabilização civil e criminal, conforme previsto pela legislação brasileira.\n'+
'10. SANÇÕES\n'+
'10.1. Em caso de descumprimento de qualquer das disposições deste TERMO, o VOLUNTÁRIO está ciente de que poderá ser desligado do programa de voluntariado.\n'+
'10.2. O desligamento do VOLUNTÁRIO que descumprir o disposto neste TERMO não excluirá possível responsabilização civil e/ou criminal determinada em lei a depender ato que for praticado.\n'+
'11. DISPOSIÇÕES GERAIS\n'+
'11.1. Alteração. O presente TERMO somente poderá ser validamente alterado, modificado ou aditado por manifestação expressa, mediante instrumento escrito devidamente assinado pelas PARTES.\n'+
'11.2. Efeito Vinculante. O presente TERMO vincula as PARTES e seus sucessores a qualquer título, em caráter irrevogável e irretratável, ao fiel cumprimento deste TERMO.\n'+
'11.3. Tolerância. A tolerância de qualquer das PARTES com relação à exigência do regular e tempestivo cumprimento das obrigações de outra PARTE não constituirá desistência, alteração, modificação, ou novação de quaisquer dos direitos ou obrigações estabelecidos por meio deste TERMO, constituindo mera liberdade, que não impedirá a PARTE tolerante de exigir da outra o fiel e cabal cumprimento deste TERMO, a qualquer tempo.\n'+
'11.4. Renúncia. Nenhuma renúncia ao exercício de direito assegurado neste TERMO será válida, exceto se formalizada por escrito pela PARTE renunciante.\n'+
'11.5. Invalidade Parcial. A invalidade parcial deste TERMO não o afetará na parte considerada válida, desde que as obrigações sejam desmembráveis entre si. Ocorrendo o disposto nesta Cláusula, as PARTES desde já se comprometem a negociar, no menor prazo possível, em substituição à Cláusula invalidada, a inclusão de termos e condições válidos que reflitam os termos e condições da Cláusula invalidada, observado o objetivo e a intenção das PARTES quando da negociação da Cláusula invalidada e o contexto em que se insere.\n'+
'11.6. Autonomia das Partes. As PARTES declaram, para todos os efeitos, que são independentes e autônomas, de forma que o presente TERMO não cria qualquer outra modalidade de vínculo entre ambas, inclusive, sem limitação, mandato, sociedade, associação, parceria, consórcio, joint-venture ou representação comercial entre as PARTES. Cada PARTE é totalmente responsável por seus atos e obrigações assumidos por meio deste TERMO. As PARTES reconhecem que elas não têm nenhuma autoridade ou poder para, direta ou indiretamente, negociar, contratar, assumir qualquer tipo de obrigação ou criar responsabilidade em nome da outra PARTE, sob hipótese alguma.\n'+
'11.7. Desvinculação Trabalhista. As PARTES reconhecem não existir qualquer vínculo de natureza trabalhista e/ou de subordinação jurídica e econômica na presente prestação de serviços entre as PARTES, bem como entre seus empregados e/ou prestadores de serviços, assumindo cada PARTE integral responsabilidade pelos encargos trabalhistas, securitários, acidentários e previdenciários de toda a mão de obra por ela contratada para execução do objeto do presente TERMO.\n'+
'11.8. Responsabilidade. Cada PARTE compromete-se indenizar e manter a PARTE contrária indene de quaisquer perdas, danos, obrigações, responsabilidades, incluindo custas judiciais e honorários advocatícios sucumbenciais, incorridos em decorrência de (i) quaisquer atos ou omissões comprovadamente praticados pela PARTE contrária, (ii) quaisquer reclamações, demandas, processos judiciais ou ações sofridas pela PARTE prejudicada decorrentes de quaisquer obrigações da PARTE contrária; e (iii) quaisquer violações pela PARTE contrária de obrigações assumidas neste TERMO, de leis ou regulamentos aplicáveis.\n'+
'11.9. Tributos. Todos os tributos e encargos fiscais devidos em razão deste TERMO serão de exclusiva responsabilidade do contribuinte definido pela legislação tributária.\n'+
'11.10. Notificações. Todas as notificações e comunicações exigidas ou permitidas neste TERMO deverão ser enviadas por escrito e entregues a cada PARTE nos endereços mencionados neste TERMO, com confirmação de recebimento.\n'+
'11.11. Atualização de dados cadastrais. Incumbe às PARTES o dever de manter as suas informações para envio de notificações devidamente atualizadas, sob pena de ser considerada entregue uma notificação encaminhada para endereço não atualizado.\n'+
'11.12. Representação. As Partes declaram, sob as penas da Lei, que os signatários deste Termo são seus representantes legais, devidamente constituídos na forma dos respectivos Estatutos/Termos Sociais, com poderes para assumir as obrigações ora contraídas.\n'+
'11.13. Mútuo Acordo. As PARTES declaram e reconhecem que entenderam perfeitamente o sentido e o alcance de todas as cláusulas e condições convencionadas no presente TERMO, obrigando-se a cumpri-las fielmente em atenção aos princípios da boa-fé e lealdade, abstendo-se de invocar, no futuro, ressalvas, oposições ou exceções que impliquem em modificação das convenções ora celebradas ou que pretendam interpretá-las de forma diversa daquela literalmente convencionada.\n'+
'11.14. Anexos e Links. Todos os Anexos e Links mencionados neste TERMO são parte integrante e indissociável deste. No caso de controvérsias entre as disposições deste TERMO e de seus Anexos e Links, as disposições deste TERMO deverão prevalecer, a não ser que sejam texto legal vigente.\n'+
'11.15. Aceite. As PARTES, em conjunto, decidem que a declaração de concordância do presente TERMO pelo VOLUNTÁRIO significa que as PARTES declaram e reconhecem a validade, para todos os fins, deste TERMO, de tal forma que uma vez dado o aceite, o TERMO produzirá todos os seus efeitos de direito.\n'+
'11.16. Veracidade das Informações. As PARTES afirmam que todas as informações prestadas entre si neste TERMO, assim como fora dele, são verdadeiras, se submetendo à responsabilização civil e/ou penal caso contrário. Isso inclui, em especial, a declaração de que o VOLUNTÁRIO está regularmente inscrito no CFP, estando autorizado pelo órgão de classe aplicável a exercer a psicologia.\n'+
'11.17. Lei Aplicável e Foro. Este TERMO será regido e interpretado de acordo com as leis da República Federativa do Brasil. Elegemos o Foro da Comarca de Londrina, Estado do Paraná, para dirimir todas as questões dele oriundas, com exclusão de qualquer outro, por mais privilegiado que seja.'